### ISSUE TITLE
Exception java.lang.StringIndexOutOfBoundsException: length=11; regionStart=7; regionLength=-6

### ISSUE THREAD

**Issue by Ivan-Loukin** [philliphsu/BottomSheetPickers#17]
Just noticed this in my firebase Crash Reporting.

com.philliphsu.bottomsheetpickers.date.BottomSheetDatePickerDialog.updateDisplay (BottomSheetDatePickerDialog.java:444)
com.philliphsu.bottomsheetpickers.date.BottomSheetDatePickerDialog.onCreateView (BottomSheetDatePickerDialog.java:291)

Unfortunately, I can't reproduce it for myself, now, to give you more information about inputs and extra.
But I hope it will be helpful to you.
Thanks.

**Comment by philliphsu** [comment]
This is likely related to the formatting of the date as displayed in the user's locale. Do you know what locale/language this occurred in?

**Comment by iballan** [comment]
I got the same error on Localization of `Locale.ENGLISH`, and on `new Locale("tr")`
@philliphsu 
 any hint how can we solve this problem ?

**Comment by iballan** [comment]
this is the stacktrace : 
```
E/AndroidRuntime: FATAL EXCEPTION: main
	Process: com.test.t, PID: 12091
	java.lang.StringIndexOutOfBoundsException: length=11; regionStart=7; regionLength=-6
	at java.lang.String.substring(String.java:1931)
	at com.philliphsu.bottomsheetpickers.date.DatePickerDialog.updateDisplay(DatePickerDialog.java:520)
	at com.philliphsu.bottomsheetpickers.date.DatePickerDialog.onCreateView(DatePickerDialog.java:366)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by iballan** [comment]
there may be an option to pass the Locale, rather than setting it to devices Default. @philliphsu

**Comment by philliphsu** [comment]
@iballan Is this for Turkey? In Turkey, I found that the standalone month-day and/or standalone year are formatted differently than they appear in the full formatted date. I implemented a workaround to address this, but I don't know why that didn't execute for you.

**Comment by philliphsu** [comment]
The issue has been fixed. The problem was formatting dates for Turkey returns different results between API 21+ and earlier versions of the platform.

**Comment by iballan** [comment]
@philliphsu thank you for the fix 👍
