### ISSUE TITLE
ClassCastException on android 7

### ISSUE THREAD

**Issue by frankhaykku** [philliphsu/BottomSheetPickers#18]
Have a problem with android 7. When I select a date and press "OK" app is crash.

> java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.support.graphics.drawable.VectorDrawableCompat
                                                                           at com.philliphsu.bottomsheetpickers.time.grid.GridTimePickerDialog.updateAmPmDisplay(GridTimePickerDialog.java:420)
                                                                           at com.philliphsu.bottomsheetpickers.time.grid.GridTimePickerDialog.onCreateView(GridTimePickerDialog.java:395)
                                                                           at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                           at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                                                           at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                                                           at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

On other APIs it work fine. Have some idea how to fix it ?
P.S. Sorry for my bad language :)

**Comment by philliphsu** [comment]
This was fixed in version 2.3.2.

**Comment by frankhaykku** [comment]
Thanks for quick response. It was my fault, I forgot to update a library!
