### ISSUE TITLE
FATAL EXCEPTION: android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by pasaneramusugoda** [philliphsu/BottomSheetPickers#8]
```
GridTimePickerDialog time = GridTimePickerDialog.newInstance(
                new BottomSheetTimePickerDialog.OnTimeSetListener() {
                    @Override
                    public void onTimeSet(ViewGroup viewGroup, int hourOfDay, int minute) {
                        mBookingDateTime.set(Calendar.HOUR_OF_DAY, hourOfDay);
                        mBookingDateTime.set(Calendar.MINUTE, minute);

                        mTextTime.setText(DateFormat.format("hh:mm", mBookingDateTime.getTime()));
                        mTextAmPm.setText(DateFormat.format("a", mBookingDateTime.getTime()));
                    }
                },
                mBookingDateTime.get(Calendar.HOUR_OF_DAY),
                mBookingDateTime.get(Calendar.MINUTE),
                false); //DateFormat.is24HourFormat(mContext)
        time.setCancelable(true);
        time.show(getChildFragmentManager(), TAG);
```

**Error:**
E/AndroidRuntime: FATAL EXCEPTION: main
                  android.content.res.Resources$NotFoundException: File res/drawable/ic_minus_circle_24dp.xml from drawable resource ID #0x7f020090. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
                      at android.content.res.Resources.loadDrawable(Resources.java:2103)
                      at android.content.res.Resources.getDrawable(Resources.java:702)
                      at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
                      at com.philliphsu.bottomsheetpickers.Utils.getTintedDrawable(Utils.java:255)
                      at com.philliphsu.bottomsheetpickers.time.grid.MinutesGrid.setTheme(MinutesGrid.java:99)
                      at com.philliphsu.bottomsheetpickers.time.grid.GridPickerLayout.setTheme(GridPickerLayout.java:116)
                      at com.philliphsu.bottomsheetpickers.time.grid.GridTimePickerDialog.onCreateView(GridTimePickerDialog.java:331)
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541)
                      at android.os.Handler.handleCallback(Handler.java:730)
                      at android.os.Handler.dispatchMessage(Handler.java:92)
                      at android.os.Looper.loop(Looper.java:213)
                      at android.app.ActivityThread.main(ActivityThread.java:5225)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:525)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
                      at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:925)
                      at android.graphics.drawable.Drawable.createFromXml(Drawable.java:853)
                      at android.content.res.Resources.loadDrawable(Resources.java:2099)
                      at android.content.res.Resources.getDrawable(Resources.java:702) 
                      at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374) 
                      at com.philliphsu.bottomsheetpickers.Utils.getTintedDrawable(Utils.java:255) 
                      at com.philliphsu.bottomsheetpickers.time.grid.MinutesGrid.setTheme(MinutesGrid.java:99) 
                      at com.philliphsu.bottomsheetpickers.time.grid.GridPickerLayout.setTheme(GridPickerLayout.java:116) 
                      at com.philliphsu.bottomsheetpickers.time.grid.GridTimePickerDialog.onCreateView(GridTimePickerDialog.java:331) 
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295) 
                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801) 
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682) 
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541) 
                      at android.os.Handler.handleCallback(Handler.java:730) 
                      at android.os.Handler.dispatchMessage(Handler.java:92) 
                      at android.os.Looper.loop(Looper.java:213) 
                      at android.app.ActivityThread.main(ActivityThread.java:5225) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:525) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by philliphsu** [comment]
Fix is upcoming.

**Comment by philliphsu** [comment]
Will be releasing in v2.0.2.
